# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: ignore
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/sorbet/all/sorbet.rbi
#
# sorbet-0.5.9914

module Stick
  def play(code, filename = nil, env: nil); end
  def self.play(code, filename = nil, env: nil); end
end
class Stick::Error < RuntimeError
end
class Stick::RunError < Stick::Error
  def backtrace; end
  def full_message; end
  def initialize(message, backtrace); end
end
class Stick::Environment
  def self.define(name, **, &&); end
end
class Stick::Environment::UnknownVariable < Stick::RunError
  def initialize(name, callstack); end
  def name; end
end
