module Stick
  class Error < RuntimeError
  end

  class RunError < Error
    attr_reader backtrace: Array[SourceLocation]

    def initialize: (String message, Array[SourceLocation] backtrace) -> void
    def full_message: () -> String
  end
end
