module Stick
  class SourceLocation
    attr_reader filename: String
    attr_reader lineno: Integer

    def initialize: (String filename, Integer lineno) -> void

    def to_s: () -> String
    def error: (String message) -> bot
  end

  class Parser
    class ParseError < Error
    end

    def initialize: (String stream, String filename) -> void
    def location: () -> SourceLocation
    def parse: () -> Group

    private

    def next_word: () -> String?
    def next_token: () -> Value?
  end
end
